import { db } from "../firebase/firebase";
import { collection, addDoc, serverTimestamp } from "firebase/firestore";

const SAMPLE_HOST_ID = "WMdkYEhTTrYUsHw9XpeH3xw1T9s2";

// Sample Stays Listings (10 records)
const staysListings = [
  {
    type: "stays",
    title: "Cozy Downtown Apartment",
    description: "Modern apartment in the heart of downtown with great views and easy access to restaurants.",
    location: "123 Main Street, New York, NY 10001",
    price: 120,
    numberOfGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    amenities: ["WiFi", "Kitchen", "Air Conditioning", "Washer/Dryer"],
    houseRules: ["No Smoking", "No Parties"],
    photos: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-11-15" },
      { startDate: "2025-11-20", endDate: "2025-12-10" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 0 },
    ratings: 4.8,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Luxury Beachfront Villa",
    description: "Stunning beachfront villa with private pool and ocean view. Perfect for families.",
    location: "456 Beach Lane, Miami, FL 33139",
    price: 350,
    numberOfGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    beds: 6,
    amenities: ["WiFi", "Pool", "Hot Tub", "Kitchen", "Beach Access", "Air Conditioning"],
    houseRules: ["No Smoking", "Respect Neighbors"],
    photos: ["https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-05", endDate: "2026-02-28" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 10 },
    ratings: 4.9,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Mountain Cabin Retreat",
    description: "Peaceful mountain cabin surrounded by nature. Great for hiking and relaxation.",
    location: "789 Pine Road, Boulder, CO 80301",
    price: 95,
    numberOfGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 4,
    amenities: ["WiFi", "Fireplace", "Kitchen", "Deck", "Mountain View"],
    houseRules: ["No Pets", "Quiet Hours After 10 PM"],
    photos: ["https://images.unsplash.com/photo-1465146072230-91cabc968266?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-11-30" },
      { startDate: "2025-12-15", endDate: "2026-01-31" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 0 },
    ratings: 4.7,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Historic Brownstone",
    description: "Beautiful historic brownstone in Brooklyn with original hardwood floors and modern amenities.",
    location: "321 Prospect Park West, Brooklyn, NY 11215",
    price: 180,
    numberOfGuests: 5,
    bedrooms: 3,
    bathrooms: 2,
    beds: 3,
    amenities: ["WiFi", "Kitchen", "Garden", "Hardwood Floors", "Heating"],
    houseRules: ["No Smoking", "Check-out by 11 AM"],
    photos: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-20" },
      { startDate: "2026-01-10", endDate: "2026-03-15" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 5 },
    ratings: 4.6,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Stylish Loft in Arts District",
    description: "Industrial-style loft in trendy arts district with high ceilings and exposed brick.",
    location: "567 Gallery Street, Los Angeles, CA 90012",
    price: 140,
    numberOfGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    amenities: ["WiFi", "Kitchen", "Rooftop Access", "Exposed Brick", "Air Conditioning"],
    houseRules: ["No Smoking", "No Large Parties"],
    photos: ["https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-11-25" },
      { startDate: "2025-12-05", endDate: "2026-01-30" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 0 },
    ratings: 4.5,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Charming Victorian Home",
    description: "Beautifully restored Victorian home with vintage charm and modern comfort.",
    location: "892 Oak Avenue, San Francisco, CA 94102",
    price: 200,
    numberOfGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 4,
    amenities: ["WiFi", "Kitchen", "Fireplace", "Garden", "Heating"],
    houseRules: ["No Smoking", "Respect Historic Property"],
    photos: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-15", endDate: "2026-04-30" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 15 },
    ratings: 4.8,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Modern City Penthouse",
    description: "Sleek penthouse with floor-to-ceiling windows and panoramic city views.",
    location: "234 Tower Avenue, Chicago, IL 60601",
    price: 280,
    numberOfGuests: 5,
    bedrooms: 3,
    bathrooms: 2,
    beds: 3,
    amenities: ["WiFi", "Kitchen", "Concierge", "Gym Access", "City View"],
    houseRules: ["No Smoking", "Check-in After 3 PM"],
    photos: ["https://images.unsplash.com/photo-1571508601596-6f8fc0d90a57?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-11-20" },
      { startDate: "2025-12-01", endDate: "2026-02-15" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 0 },
    ratings: 4.9,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Rustic Farm House",
    description: "Peaceful farm stay with organic gardens and farm-fresh breakfast included.",
    location: "123 Country Lane, Napa, CA 94558",
    price: 150,
    numberOfGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 4,
    amenities: ["WiFi", "Kitchen", "Garden", "Breakfast Included", "Scenic Views"],
    houseRules: ["No Smoking", "Respect Farm Animals"],
    photos: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2026-01-31" },
      { startDate: "2026-02-15", endDate: "2026-05-30" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 0 },
    ratings: 4.7,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Waterfront Cottage",
    description: "Charming cottage right on the water with private dock and kayak access.",
    location: "456 Lake View Drive, Seattle, WA 98101",
    price: 165,
    numberOfGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    amenities: ["WiFi", "Kitchen", "Dock", "Kayak Access", "Water View"],
    houseRules: ["No Smoking", "Quiet Evenings"],
    photos: ["https://images.unsplash.com/photo-1570129477992-45667601a3ee?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-15" },
      { startDate: "2026-01-05", endDate: "2026-03-31" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 10 },
    ratings: 4.8,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "stays",
    title: "Desert Oasis Villa",
    description: "Stunning villa in the desert with pool, hot tub, and breathtaking sunset views.",
    location: "789 Desert Rose Lane, Phoenix, AZ 85001",
    price: 220,
    numberOfGuests: 7,
    bedrooms: 3,
    bathrooms: 3,
    beds: 4,
    amenities: ["WiFi", "Pool", "Hot Tub", "Kitchen", "Desert View"],
    houseRules: ["No Smoking", "Pool Rules Apply"],
    photos: ["https://images.unsplash.com/photo-1501877442353-cebf8dd7f001?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-10", endDate: "2026-04-15" }
    ],
    bookedDates: [],
    promoCode: null,
    discount: { type: "percentage", value: 20 },
    ratings: 4.9,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  }
];

// Sample Experiences Listings (10 records)
const experiencesListings = [
  {
    type: "experiences",
    title: "NYC Food Tour",
    description: "Explore the best street food and local restaurants with a professional guide.",
    location: "Times Square, New York, NY 10036",
    price: 85,
    duration: 3,
    maxGuests: 12,
    category: "Food",
    language: "English",
    ageMin: 10,
    activities: ["Street Food Tasting", "Local Restaurant Visit", "Cultural Stories", "Food Photography"],
    thingsToKnow: ["Comfortable walking shoes required", "Bring water bottle", "Tours run rain or shine"],
    included: ["All tastings", "Local guide", "Walking tour", "City map"],
    toBring: ["Camera", "Comfortable shoes", "Water bottle"],
    photos: ["https://images.unsplash.com/photo-1504674900761-655147302605?w=800&q=80"],
    availableTimes: ["10:00", "14:00", "18:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-11-30" },
      { startDate: "2025-12-05", endDate: "2026-01-31" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    rating: 4.8,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Surfing Lessons in Hawaii",
    description: "Learn to surf with experienced instructors on beautiful Hawaiian beaches.",
    location: "Waikiki Beach, Honolulu, HI 96815",
    price: 65,
    duration: 2,
    maxGuests: 8,
    category: "Adventure",
    language: "English",
    ageMin: 8,
    activities: ["Surfing Instruction", "Beach Safety", "Wave Reading", "Photo Session"],
    thingsToKnow: ["Swimwear required", "Can you swim?", "Bring sunscreen"],
    included: ["Surfboard rental", "Instructor", "Equipment", "Photos"],
    toBring: ["Swimwear", "Towel", "Sunscreen", "Cash for tips"],
    photos: ["https://images.unsplash.com/photo-1571888677073-e62d0236c7be?w=800&q=80"],
    availableTimes: ["06:00", "10:00", "14:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2026-02-28" },
      { startDate: "2026-03-15", endDate: "2026-05-31" }
    ],
    discount: { type: "percentage", value: 5 },
    promoCode: null,
    rating: 4.9,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Wine Tasting in Napa Valley",
    description: "Visit 3 local wineries with expert sommelier and gourmet lunch included.",
    location: "Napa Valley, CA 94558",
    price: 150,
    duration: 5,
    maxGuests: 10,
    category: "Food",
    language: "English",
    ageMin: 21,
    activities: ["Winery Tour", "Wine Tasting", "Sommelier Talk", "Gourmet Lunch"],
    thingsToKnow: ["Minimum age 21", "Driver recommended", "Wear comfortable shoes"],
    included: ["3 winery visits", "Tastings", "Lunch", "Transportation"],
    toBring: ["ID", "Camera", "Comfortable clothes"],
    photos: ["https://images.unsplash.com/photo-1510812431401-41d2bd2e3868?w=800&q=80"],
    availableTimes: ["09:00", "13:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-20" },
      { startDate: "2026-01-10", endDate: "2026-04-30" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    rating: 4.9,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Hot Air Balloon Ride",
    description: "Experience breathtaking views from a hot air balloon at sunrise.",
    location: "Scottsdale, AZ 85251",
    price: 200,
    duration: 1,
    maxGuests: 4,
    category: "Adventure",
    language: "English",
    ageMin: 5,
    activities: ["Balloon Setup", "Flight Experience", "Sunrise Views", "Champagne Toast"],
    thingsToKnow: ["Early morning", "Wear layers", "Not for acrophobics"],
    included: ["Balloon ride", "Pilot", "Champagne", "Photos"],
    toBring: ["Comfortable clothes", "Light jacket", "Camera"],
    photos: ["https://images.unsplash.com/photo-1578575437980-ba2b2fac3c6d?w=800&q=80"],
    availableTimes: ["06:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-11-30" },
      { startDate: "2026-01-05", endDate: "2026-03-31" }
    ],
    discount: { type: "percentage", value: 10 },
    promoCode: null,
    rating: 4.95,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Cooking Class with Michelin Chef",
    description: "Learn cooking techniques from a Michelin-starred chef in an intimate setting.",
    location: "Mission District, San Francisco, CA 94103",
    price: 120,
    duration: 3,
    maxGuests: 8,
    category: "Food",
    language: "English",
    ageMin: 16,
    activities: ["Hands-On Cooking", "Chef Instruction", "Meal Preparation", "Tasting"],
    thingsToKnow: ["Apron provided", "Basic cooking skills", "Dietary restrictions noted"],
    included: ["All ingredients", "Equipment", "Apron", "Meal to eat"],
    toBring: ["Nothing needed"],
    photos: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80"],
    availableTimes: ["11:00", "15:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-15", endDate: "2026-03-30" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    rating: 4.8,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Historical Walking Tour",
    description: "Discover the rich history and hidden gems of the city with a knowledgeable guide.",
    location: "Downtown Boston, MA 02108",
    price: 45,
    duration: 2.5,
    maxGuests: 15,
    category: "Culture",
    language: "English",
    ageMin: 0,
    activities: ["Historical Sites", "Local Stories", "Architecture Tour", "Photo Stops"],
    thingsToKnow: ["Moderate walking", "Comfortable shoes", "Weather dependent"],
    included: ["Guided tour", "Historical facts", "Maps"],
    toBring: ["Comfortable shoes", "Water", "Camera"],
    photos: ["https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80"],
    availableTimes: ["10:00", "14:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-05", endDate: "2026-05-31" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    rating: 4.7,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Yoga Retreat in Bali",
    description: "5-day yoga retreat with meditation, spa, and tropical island experience.",
    location: "Ubud, Bali, Indonesia",
    price: 450,
    duration: 5,
    maxGuests: 20,
    category: "Wellness",
    language: "English",
    ageMin: 18,
    activities: ["Yoga Sessions", "Meditation", "Spa Treatments", "Beach Visit", "Cultural Tour"],
    thingsToKnow: ["Accommodation included", "Flexible schedule", "Bring yoga mat"],
    included: ["Accommodation", "All meals", "Yoga classes", "Spa", "Excursions"],
    toBring: ["Yoga clothes", "Mat", "Toiletries", "Light clothes"],
    photos: ["https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80"],
    availableTimes: ["08:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-11-30" },
      { startDate: "2026-01-10", endDate: "2026-02-28" }
    ],
    discount: { type: "percentage", value: 15 },
    promoCode: null,
    rating: 4.9,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Rock Climbing Adventure",
    description: "Guided rock climbing experience for beginners and experienced climbers.",
    location: "Moab, UT 84532",
    price: 95,
    duration: 4,
    maxGuests: 6,
    category: "Adventure",
    language: "English",
    ageMin: 12,
    activities: ["Climbing", "Belay Training", "Safety Brief", "Nature Exploration"],
    thingsToKnow: ["Physical activity", "Climbing shoes provided", "Fear of heights okay"],
    included: ["Equipment", "Guide", "Instruction", "Harness"],
    toBring: ["Water", "Snacks", "Comfortable clothes"],
    photos: ["https://images.unsplash.com/photo-1551958219-acbc608c6be4?w=800&q=80"],
    availableTimes: ["08:00", "13:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-11-30" },
      { startDate: "2025-12-10", endDate: "2026-01-31" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    rating: 4.8,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Safari Adventure",
    description: "3-day guided safari with wildlife viewing and luxury lodge accommodation.",
    location: "Serengeti, Tanzania",
    price: 650,
    duration: 3,
    maxGuests: 8,
    category: "Adventure",
    language: "English",
    ageMin: 6,
    activities: ["Game Drives", "Wildlife Viewing", "Photography", "Nature Walks"],
    thingsToKnow: ["Accommodation included", "Early starts", "Bring binoculars"],
    included: ["Lodge", "All meals", "Game drives", "Guide", "Transportation"],
    toBring: ["Camera", "Binoculars", "Sun protection", "Neutral colors"],
    photos: ["https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80"],
    availableTimes: ["06:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-15" },
      { startDate: "2026-01-20", endDate: "2026-03-31" }
    ],
    discount: { type: "percentage", value: 20 },
    promoCode: null,
    rating: 4.95,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  },
  {
    type: "experiences",
    title: "Art Workshop and Gallery Tour",
    description: "Create your own art piece with a professional artist and tour local galleries.",
    location: "Chelsea, New York, NY 10011",
    price: 75,
    duration: 3,
    maxGuests: 10,
    category: "Culture",
    language: "English",
    ageMin: 10,
    activities: ["Art Creation", "Professional Guidance", "Gallery Tour", "Art Discussion"],
    thingsToKnow: ["No art experience needed", "Materials provided", "Wear old clothes"],
    included: ["Art supplies", "Instruction", "Gallery admission", "Snacks"],
    toBring: ["Nothing required"],
    photos: ["https://images.unsplash.com/photo-1561214115-6d2f1b0609fa?w=800&q=80"],
    availableTimes: ["10:00", "14:00"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2026-01-31" },
      { startDate: "2026-02-15", endDate: "2026-04-30" }
    ],
    discount: { type: "percentage", value: 5 },
    promoCode: null,
    rating: 4.7,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  }
];

// Sample Services Listings (10 records)
const servicesListings = [
  {
    type: "services",
    title: "Professional House Cleaning",
    description: "Thorough house cleaning with eco-friendly products and professional team.",
    location: "Los Angeles, CA 90001",
    price: 45,
    duration: 3,
    category: "Home Services",
    responseTime: "within 2 hours",
    serviceTypes: ["Deep Cleaning", "Regular Cleaning", "Move-Out Cleaning"],
    highlights: ["Eco-friendly products", "Experienced team", "Quick turnaround"],
    serviceAreas: ["Los Angeles", "Santa Monica", "Beverly Hills"],
    certifications: ["Certified Cleaner", "Bio-Safe Certified"],
    terms: ["Minimum 3 hours", "Cancellation 24 hours notice"],
    experienceYears: 8,
    completedJobs: 450,
    photos: ["https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-05", endDate: "2026-06-30" }
    ],
    discount: { type: "percentage", value: 10 },
    promoCode: null,
    isVerified: true,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "Plumbing Services",
    description: "Emergency and scheduled plumbing repairs, installations, and maintenance.",
    location: "New York, NY 10001",
    price: 75,
    duration: 2,
    category: "Home Services",
    responseTime: "within 1 hour",
    serviceTypes: ["Repairs", "Installation", "Maintenance", "Emergency Service"],
    highlights: ["24/7 Emergency service", "Licensed", "Guaranteed work"],
    serviceAreas: ["New York", "New Jersey", "Connecticut"],
    certifications: ["Licensed Plumber", "Master Plumber"],
    terms: ["Emergency fees apply", "Estimates provided"],
    experienceYears: 15,
    completedJobs: 800,
    photos: ["https://images.unsplash.com/photo-1559056199-641a0ac8b8d5?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-05", endDate: "2026-06-30" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    isVerified: true,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "Personal Training",
    description: "Customized fitness training programs tailored to your goals and fitness level.",
    location: "Chicago, IL 60601",
    price: 55,
    duration: 1,
    category: "Fitness",
    responseTime: "within 24 hours",
    serviceTypes: ["Weight Training", "Cardio", "HIIT", "Yoga", "Flexibility"],
    highlights: ["Personalized plans", "Nutrition advice", "Progress tracking"],
    serviceAreas: ["Chicago", "Suburbs"],
    certifications: ["ACE Certified", "CPT Certified"],
    terms: ["Minimum 1 hour session", "Flexible scheduling"],
    experienceYears: 6,
    completedJobs: 350,
    photos: ["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2026-01-31" },
      { startDate: "2026-02-15", endDate: "2026-06-30" }
    ],
    discount: { type: "percentage", value: 5 },
    promoCode: null,
    isVerified: false,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "Electrical Services",
    description: "Professional electrical installation, repairs, and maintenance services.",
    location: "Houston, TX 77002",
    price: 65,
    duration: 2,
    category: "Home Services",
    responseTime: "within 4 hours",
    serviceTypes: ["Installation", "Repairs", "Maintenance", "Troubleshooting"],
    highlights: ["Licensed electrician", "Fast service", "Code compliant"],
    serviceAreas: ["Houston", "Surrounding areas"],
    certifications: ["Licensed Electrician", "Master Electrician"],
    terms: ["Minimum 1 hour", "Estimates free"],
    experienceYears: 12,
    completedJobs: 620,
    photos: ["https://images.unsplash.com/photo-1581578731548-c64695c952952?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-05", endDate: "2026-06-30" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    isVerified: true,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "Pet Care and Dog Walking",
    description: "Daily dog walking, pet sitting, and care services for your beloved pets.",
    location: "San Francisco, CA 94102",
    price: 25,
    duration: 0.5,
    category: "Pet Services",
    responseTime: "within 3 hours",
    serviceTypes: ["Dog Walking", "Pet Sitting", "Feeding", "Play Sessions"],
    highlights: ["Insured", "Loving care", "Photo updates"],
    serviceAreas: ["San Francisco", "Oakland"],
    certifications: ["Pet First Aid", "Dog Behavior Certified"],
    terms: ["Minimum 30 minutes", "Same-day booking available"],
    experienceYears: 4,
    completedJobs: 520,
    photos: ["https://images.unsplash.com/photo-1560244018-be2dfc253c82?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2026-03-31" },
      { startDate: "2026-04-15", endDate: "2026-08-31" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    isVerified: true,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "Photography Services",
    description: "Professional photography for portraits, events, and special occasions.",
    location: "Seattle, WA 98101",
    price: 80,
    duration: 2,
    category: "Creative Services",
    responseTime: "within 24 hours",
    serviceTypes: ["Portrait", "Event", "Wedding", "Product Photography"],
    highlights: ["Professional equipment", "Quick editing", "Digital copies"],
    serviceAreas: ["Seattle", "Pacific Northwest"],
    certifications: ["Professional Photographer", "Adobe Certified"],
    terms: ["Minimum 2 hours", "Deposit required"],
    experienceYears: 9,
    completedJobs: 380,
    photos: ["https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-15", endDate: "2026-06-30" }
    ],
    discount: { type: "percentage", value: 15 },
    promoCode: null,
    isVerified: true,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "Tutoring and Academic Help",
    description: "Expert tutoring in math, science, languages, and SAT/ACT prep.",
    location: "Boston, MA 02108",
    price: 50,
    duration: 1,
    category: "Education",
    responseTime: "within 2 hours",
    serviceTypes: ["Math", "Science", "Languages", "Test Prep"],
    highlights: ["Expert instructors", "Flexible scheduling", "Proven results"],
    serviceAreas: ["Boston", "Suburbs", "Online"],
    certifications: ["Subject Matter Expert", "Teaching Certified"],
    terms: ["Minimum 1 hour", "30-minute free trial"],
    experienceYears: 7,
    completedJobs: 420,
    photos: ["https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2026-02-28" },
      { startDate: "2026-03-15", endDate: "2026-06-30" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    isVerified: false,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "Hair and Beauty Services",
    description: "Professional hair styling, coloring, and beauty treatments.",
    location: "Miami, FL 33139",
    price: 60,
    duration: 1.5,
    category: "Beauty Services",
    responseTime: "within 6 hours",
    serviceTypes: ["Hair Cut", "Coloring", "Styling", "Makeup", "Treatments"],
    highlights: ["Premium products", "Latest trends", "Luxury experience"],
    serviceAreas: ["Miami", "South Beach"],
    certifications: ["Master Stylist", "Color Expert"],
    terms: ["Consultation available", "Rescheduling allowed"],
    experienceYears: 11,
    completedJobs: 890,
    photos: ["https://images.unsplash.com/photo-1566613535308-ee0db6cb3808?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2025-12-31" },
      { startDate: "2026-01-05", endDate: "2026-06-30" }
    ],
    discount: { type: "percentage", value: 10 },
    promoCode: null,
    isVerified: true,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "HVAC and Air Conditioning",
    description: "HVAC installation, repair, and maintenance services year-round.",
    location: "Phoenix, AZ 85001",
    price: 70,
    duration: 2,
    category: "Home Services",
    responseTime: "within 2 hours",
    serviceTypes: ["Installation", "Repair", "Maintenance", "Emergency Service"],
    highlights: ["24/7 service", "Licensed technician", "Warranty"],
    serviceAreas: ["Phoenix", "Scottsdale", "Arizona"],
    certifications: ["EPA Certified", "HVAC Licensed"],
    terms: ["Emergency surcharge", "Maintenance plans available"],
    experienceYears: 13,
    completedJobs: 750,
    photos: ["https://images.unsplash.com/photo-1580828343064-fde4fc206bc6?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2026-01-31" },
      { startDate: "2026-02-15", endDate: "2026-06-30" }
    ],
    discount: { type: "percentage", value: 0 },
    promoCode: null,
    isVerified: true,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  },
  {
    type: "services",
    title: "Virtual Assistant Services",
    description: "Remote administrative support, scheduling, email management, and more.",
    location: "Remote Service",
    price: 35,
    duration: 4,
    category: "Business Services",
    responseTime: "within 12 hours",
    serviceTypes: ["Email Management", "Scheduling", "Data Entry", "Customer Service"],
    highlights: ["Reliable", "Efficient", "Discreet"],
    serviceAreas: ["Remote (Worldwide)"],
    certifications: ["Administrative Professional", "Virtual Assistant Certified"],
    terms: ["Minimum 4 hours", "Monthly packages available"],
    experienceYears: 5,
    completedJobs: 280,
    photos: ["https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80"],
    availableDates: [
      { startDate: "2025-10-28", endDate: "2026-03-31" },
      { startDate: "2026-04-15", endDate: "2026-08-31" }
    ],
    discount: { type: "percentage", value: 5 },
    promoCode: null,
    isVerified: false,
    isDraft: false,
    status: "active",
    hostId: SAMPLE_HOST_ID,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp()
  }
];

// Function to add all sample listings to Firestore
export const addSampleListings = async () => {
  try {
    console.log("Starting to add sample listings...");

    const allListings = [...staysListings, ...experiencesListings, ...servicesListings];
    let successCount = 0;
    let errorCount = 0;

    for (const listing of allListings) {
      try {
        const docRef = await addDoc(collection(db, "listings"), listing);
        console.log(`Added ${listing.type} listing:`, docRef.id);
        successCount++;
      } catch (error) {
        console.error(`Error adding ${listing.type} listing:`, error);
        errorCount++;
      }
    }

    console.log(
      `✅ Successfully added ${successCount} listings. Errors: ${errorCount}`
    );
    return { success: true, successCount, errorCount };
  } catch (error) {
    console.error("Error adding sample listings:", error);
    return { success: false, error: error.message };
  }
};
